const notes1 = [
    "Bergamot",
    "Bitter Orange",
    "Blood Orange",
    "Calamansi",
    "Candied Lemon",
    "Chen Pi",
    "Chinotto",
    "Citron",
    "Citrus Water",
    "Citruses",
    "Clementine",
    "Finger Lime",
    "Grapefruit",
    "Grapefruit Leaf",
    "Grapefruit Peel",
    "Green Tangerine",
    "Hassaku",
    "Hatkora Lemon",
    "Kaffir Lime",
    "Kumquat",
    "Lemon",
    "Lemon Balm",
    "Lemon Tree",
    "Lemon Verbena",
    "Lemon Zest",
    "Lemongrass",
    "Lime",
    "Limetta",
    "Litsea Cubeba",
    "Mandarin Orange",
    "Mandora",
    "Orange",
    "Palestinian Sweet Lime",
    "Petitgrain",
    "Pokan",
    "Pomelo",
    "Shiikuwasha",
    "Tangelo",
    "Tangerine",
    "Tangerine Zest",
    "Yuzu",
    "Acai Berry",
    "Acerola",
    "Acorn",
    "Almond",
    "Apple",
    "Apple Juice",
    "Apple Pulp",
    "Apple Sherbet",
    "Apricot",
    "Arctic Bramble",
    "Argan",
    "Artichoke",
    "Banana",
    "Barberry",
    "Bearberry",
    "Beetroot",
    "Black Cherry",
    "Black Currant",
    "Black Sapote",
    "Black Walnut",
    "Blackberry",
    "Blackthorn",
    "Blueberry",
    "Boysenberry",
    "Brazil Nut",
    "Breadnut",
    "Buriti",
    "Burning Cherry",
    "Candlenut",
    "Cantaloupe",
    "Star Fruit",
    "Carrot",
    "Cashew",
    "Cassowary Fruit",
    "Cauliflower",
    "Cepes",
    "Chayote",
    "Cherry",
    "Chestnut",
    "Chia Seed",
    "Chickpeas",
    "Chinese Magnolia",
    "Cloudberry",
    "Coco De Mer",
    "Coconut",
    "Coconut Water",
    "Conifer",
    "Corn",
    "Corn Silk",
    "Cranberry",
    "Cucumber",
    "Currant Leaf and Bud",
    "Daikon Radish",
    "Dark Plum Wu Mei",
    "Dewberry",
    "Dried Apple Crisp",
    "Dried Apricot",
    "Dried Fruits",
    "Durian",
    "Elderberry",
    "Feijoa Fruit",
    "Fig",
    "Fig Leaf",
    "Forest Fruits",
    "Frosted Berries",
    "Fruit Salad",
    "Gariguette Strawberry",
    "Genipapo",
    "Goji Berries",
    "Gooseberry",
    "Grains",
    "Grape Seed",
    "Grapes",
    "Green Anjou Pears",
    "Green Grape",
    "Green Pear",
    "Green Plum",
    "Greengage",
    "Ground Cherry",
    "Guarana",
    "Guava",
    "Hazelnut",
    "Isabella Grape",
    "Jabuticaba",
    "Jackfruit",
    "Japanese Loquat",
    "Kiwi",
    "Kumbaru",
    "Lingonberry",
    "Litchi",
    "Loganberry",
    "Longan Berries",
    "Macadamia",
    "Mahonia",
    "Malt",
    "Mango",
    "Mangosteen",
    "Maninka",
    "Marian Plum",
    "Medlar",
    "Melon",
    "Mirabelle",
    "Mulberry",
    "Mung Bean",
    "Mushroom",
    "Nashi Pear",
    "Nectarine",
    "Okra Seeds",
    "Olive",
    "Papaya",
    "Passionfruit",
    "Pea",
    "Peach",
    "Peanut",
    "Pear",
    "Pecan",
    "Persimmon",
    "Peruvian Pepper",
    "Pineapple",
    "Pinot Noir Grapes",
    "Pistachio",
    "Pitahaya",
    "Pitanga",
    "Plum",
    "Pomegranate",
    "Potato",
    "Prickly Pear",
    "Pumpkin",
    "Quandong Desert Peach",
    "Quince",
    "Rambutan",
    "Raspberry",
    "Red Apple",
    "Red Berries",
    "Red Currant",
    "Red Fruits",
    "Red Fruits Smoothie",
    "Red Mulberry",
    "Rhubarb",
    "Roasted Nuts",
    "Sapodilla",
    "Sarsaparilla",
    "Sea Buckthorn",
    "Seriguela",
    "Shea Butter",
    "Shea Nuts",
    "Silverberry",
    "Snowberry",
    "Sour Cherry",
    "Soursop",
    "Soybean",
    "Squash",
    "Star Apple",
    "Strawberry",
    "Tayberry",
    "Tomato",
    "Tropical Fruits",
    "Tucumã",
    "Walnut",
    "Walnut Milk",
    "Water Fruit",
    "Watermelon",
    "Wattleseed",
    "White Currant",
    "White Grape",
    "Wild Strawberry",
    "Williams Pear",
    "Winterberry",
    "Wolfberry",
    "Yellow Cherry",
    "Yellow Fruits",
    "Yuca Cassava",
    "Yumberry",
    "Acacia ",
    "Acerola Blossom",
    "Albizia",
    "Almond Blossom",
    "Alpinia",
    "Alstroemeria",
    "Althaea",
    "Alumroot",
    "Alyssum",
    "Amarillys",
    "Amazon Moonflower",
    "Anemone",
    "Angel's Trumpet",
    "Apple Blossom",
    "Apricot Blossom",
    "Ashoka Flower",
    "Astragalus",
    "Azalea",
    "Azteca Lily",
    "Banana Flower",
    "Banksia Australian",
    "Begonia",
    "Belladona",
    "Bellflower",
    "Bergamot Blossom",
    "Bird cherry",
    "Black Currant Blossom",
    "Blackberry Blossom",
    "Blue Lilies",
    "Blue Poppy",
    "Bottlebrush",
    "Bread Flower",
    "Buttercup",
    "Cacao Blossom",
    "Calla Lily",
    "Camellia",
    "Campion Flower",
    "Cannonball Flower",
    "Carambola Blossom",
    "Cardamom Flower",
    "Carnation",
    "Celosia",
    "Chai Hu",
    "Chamomile",
    "Champaca",
    "Cherry Blossom",
    "China Rose",
    "Chinotto blossom",
    "Chocolate Flower",
    "Chrysanthemum",
    "Cistus Incanus",
    "Clematis",
    "Clover",
    "Coconut Blossom",
    "Coffee Blossom",
    "Cosmos Flower",
    "Costus",
    "Cotton Flower",
    "Creamy Flowers",
    "Crinum Lily",
    "Cucumber Flower",
    "Cyclamen",
    "Dahlia",
    "Daisy",
    "Dandelion",
    "Daphne",
    "Daylily",
    "Deadnettle",
    "Delonix",
    "Desert Rose",
    "Dianthus",
    "Dogwood Blossom",
    "Dove Tree",
    "Dried Rose",
    "Edelweiss",
    "Eglantine Rose",
    "Elderflower",
    "Encian",
    "English Marigold",
    "Evergreen",
    "Field Scabious",
    "Fig Blossom",
    "Fire Lily",
    "Flamingo Flower",
    "Flax",
    "Forget Me Not",
    "Fragonia",
    "Freesia",
    "Fringed Pink",
    "Fuchsia",
    "Geranium",
    "Gladiolus",
    "Goldenrod",
    "Gorse",
    "Grapeflower",
    "Green Tea Flower",
    "Grevillea",
    "Guava Blossom",
    "Guayacan",
    "Gustavia Flower",
    "Hawthorn",
    "Hazel Blossom",
    "Heliotrope",
    "Hellabore Flower",
    "Hemlock",
    "Hibiscus",
    "Hoary Stock",
    "Holly Flower",
    "Hollyhock",
    "Honeydew Blossom",
    "Hortensia",
    "Hoya Carnosa Wax Plant",
    "Hyacinth",
    "Hyssop",
    "Impatiens",
    "Inula",
    "Iris",
    "Iris Butter",
    "Iris Pallida",
    "Jacaranda",
    "Jade Flower",
    "Jasmine Orchid",
    "Jujube Blossom",
    "Kadam",
    "Kangaroo Paw",
    "Kanuka",
    "Kiwi blossom",
    "Laburnum",
    "Lady of the Night Flower",
    "Lady Slipper Orchid",
    "Lamduan Flower",
    "Lamprocapnos",
    "Lantana",
    "Larkspur",
    "Laurel Blossom",
    "Lavender",
    "Leatherwood",
    "Liatris",
    "Lilac",
    "Lily-of-the-Valley",
    "Lime Blossom",
    "Litchi Blossom",
    "Lotus",
    "Lydia Broom",
    "Magnolia",
    "Magnolia Brooklynensis",
    "Magnolia Leaf",
    "Mango Blossom",
    "Mariposa Lily",
    "Mayflower",
    "Meadowsweet",
    "Melilotus",
    "Melissa Flower",
    "Michelia",
    "Mignonette",
    "Mimosa",
    "Mirabilis",
    "Monarda",
    "Morning Glory Flower",
    "Moss Flox",
    "Myrtle",
    "Narcissus",
    "Nectarine Blossom",
    "Night Blooming Jasmine",
    "Olive flower",
    "Opium",
    "Orange Cassia Tree",
    "Orange Flower Water",
    "Orange Flower Water",
    "Orchard Blossom",
    "Orchid",
    "Orchid Black Diamond",
    "Orchid Cactus",
    "Orchid Pink Leopard",
    "Osmanthus",
    "Pansy",
    "Papaya Blossom",
    "Paramela",
    "Passion Flower",
    "Pataqueira",
    "Peach Blossom",
    "Pear Blossom",
    "Pelargonium",
    "Peony",
    "Periwinkle",
    "Petunia",
    "Pineapple Blossom",
    "Pink Flamingo Heliconia",
    "Pink Lily",
    "Pittosporum",
    "Plum Blossom",
    "Plumeria",
    "Poinsettia",
    "Pomegranate Blossom",
    "Poppy",
    "Primrose",
    "Princess Tree",
    "Prunella",
    "Purple Coneflower",
    "Rangoon Creeper",
    "Raspberry Blossom",
    "Redwood Flower",
    "Rose",
    "Rose Hip",
    "Rose Japanese",
    "Rose Mallow",
    "Rosebay Willowherb",
    "Rosebud",
    "Roselle",
    "Safflower",
    "Sainfoins",
    "Sand Lily",
    "Sandalwood Flower",
    "Santolina",
    "Saucer Magnolia",
    "Sea Daffodil",
    "Silk Tree Blossom",
    "Skeleton Flower",
    "Smoketree",
    "Snakeroot",
    "Snow Lotus",
    "Snowdrops",
    "Sophora Toromiro Flower",
    "Sour Cherry Blossom",
    "Spanish Broom",
    "Spiraea",
    "Starflower",
    "Strawberry Flower",
    "Strelitzia",
    "Strobilanthes Callosa",
    "Sunflower",
    "Sweet Pea",
    "Taif Rose",
    "Tamarisk",
    "Tobacco Blossom",
    "Transparent Flowers",
    "Trillium",
    "Tulip",
    "Vanilla Bahiana",
    "Viburnum",
    "Violet",
    "Violet Woodsorrel",
    "Wallflower",
    "Waratah",
    "Water Flowers",
    "Water Hyacinth",
    "Water Lily",
    "White Dahlia",
    "White Ginger Lily",
    "White Lace Flower",
    "White Tea Blossom",
    "Wildflowers",
    "Wisteria",
    "Wrightia",
    "Yellow Bells",
    "Yellow Flowers",
    "Ylang-Ylang",
    "Yuzu Flower",
    "Zinnia",
    "Arum Lily",
    "Belanis",
    "Black Locust",
    "Boronia",
    "Carissa",
    "Datura",
    "Frangipani",
    "Gardenia",
    "Grapefruit Blossom",
    "Honeysuckle",
    "Jasmine",
    "Lemon Blossom",
    "Lily",
    "Mandarin Orange Blossom",
    "Melati",
    "Mock Orange",
    "Moon Flower",
    "Night Blooming Cereus",
    "Orange Blossom",
    "Stephanotis",
    "Syringa",
    "Tangerine Blossom",
    "Tiare Flower",
    "Tuberose",
    "White Flowers",
    "White Tobacco",
    "Agave",
    "Algae",
    "Aloe Vera",
    "Angelica",
    "Angelica Root",
    "Apple Mint",
    "Arnica",
    "Asparagus",
    "Assam Tea",
    "Avocado",
    "Banana Leaf",
    "Barley",
    "Basil",
    "Bay Essence",
    "Beachheather",
    "Betel Leaf",
    "Black Currant Leaf",
    "Blackberry Leaf",
    "Borage",
    "Borneol",
    "Bran",
    "Buckwheat",
    "Buckwheat Tea",
    "Bulrush",
    "Burdock",
    "Cactus",
    "Calamus",
    "Calycanthus",
    "Cannabis",
    "Carnation Leaves",
    "Catnip",
    "Cedar Leaves",
    "Celery",
    "Celery Seeds",
    "Centella Asiatica",
    "Cherry Leaf",
    "Chicory",
    "Chive",
    "Cilantro",
    "Citron Leaf",
    "Clary Sage",
    "Coca",
    "Deer Tongue Grass",
    "Dried Fallen Leaves",
    "Earl Grey Tea",
    "Fermented Tea",
    "Fern",
    "Flouve",
    "Fresh Evergreen",
    "Gajumaru Banyan",
    "Garlic",
    "Genmaicha",
    "Ginkgo",
    "Ginseng",
    "Grape Leaves",
    "Grass",
    "Green Branches",
    "Green Forest",
    "Green Pepper",
    "Green Sap",
    "Gromwell",
    "Hay",
    "Henna",
    "Hops",
    "Horseweed",
    "Immortelle",
    "Ivy",
    "Jambu",
    "Juniper",
    "Juniper Berries",
    "Katrafay",
    "Katsura Leaf",
    "Lantana leaf",
    "Lapsang Souchong Tea",
    "Laurissilva Forest",
    "Lesser Calamint",
    "Lettuce",
    "Lily-of-the-Valley Leaves",
    "Limnophila Aromatica",
    "Linaloe Berry",
    "Longjing Tea",
    "Lovage Root",
    "Mandrake",
    "Marigold",
    "Marjoram",
    "Matcha Tea",
    "Mimosa Leaves",
    "Mint",
    "Mistletoe",
    "Mugwort",
    "Naswar",
    "Nettle",
    "Nut Grass",
    "Oak Leaves",
    "Oat",
    "Olive Leaf",
    "Oolong Tea",
    "Orchid Leaf",
    "Oregano",
    "Palm Leaf",
    "Palmarosa",
    "Pandanus",
    "Parsley",
    "Peach Leaf",
    "Pear Leaf",
    "Pesto",
    "Petrichor",
    "Peyote",
    "Physcool",
    "Polygonum",
    "Pu'er Tea",
    "Purslane",
    "Red Algae",
    "Reed",
    "Rice",
    "Rooibos Red Tea",
    "Roots",
    "Rose Leaf",
    "Rose Thorn",
    "Rosemary",
    "Roseroot",
    "Rue",
    "Rye",
    "Sabah Snake Grass",
    "Sage",
    "Sansevieria",
    "Sap",
    "Satureja",
    "Saw Palmetto",
    "Seaweed",
    "Shiso",
    "Sideritis Mountain Tea"
];